/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'haochen' at '5/13/15 3:38 PM' with Gradle 2.3
 *
 * @author haochen, @date 5/13/15 3:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
